load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

pkg_tar(
    name = "telos_cli_bundle",
    srcs = glob(["telos-cli/**"]),
    extension = "tar.gz",
    mode = "0644",
    strip_prefix = "telos-cli",
    visibility = ["//visibility:public"],
)

pkg_tar(
    name = "telos_spec_bundle",
    srcs = glob(["telos-spec/**"]),
    extension = "tar.gz",
    mode = "0644",
    strip_prefix = "telos-spec",
    visibility = ["//visibility:public"],
)
